import Languages from "@/components/languages";

export const texts = {
    en: {
        welcome: "Welcome",
        availability: "Available",
        introH1:"I make Design that’s intuitive to use — and realistic to build.",
        introH2: "Hi, I'm Levin",
        introP: "UX/UI Designer and Frontend Developer with 13+ years of experience.",
        
        introP2: "I’m designing and building intuitive, accessible digital products from concept to production. I work at the intersection of user needs, visual design, and technical feasibility — shaping ideas through research and prototyping, then supporting clean, realistic implementation with developers (or building it myself).",
        introP3:"In short: I push pixels, ask why, and help my team ship experiences that feel good to use — and good to maintain.",
        introList1:"UX/UI Designer with strong product thinking",
        introList2:"Frontend-savvy (HTML, CSS/SCSS, React, TYPO3)",
        introList3:" Design-led, implementation-aware",
        introList4:"13+ years experience across agency & product teams",
        introList5:"Based in Europe, remote-friendly",
        ctaText:"Interested in working together?",
        ctaLabel:"I’d love to talk",
        skillsH2:"Skills",
        skillsgroup1:"Web developement",

        skillsgroup2:"UX/UI & Design",
        skillsgroup2item1:"Prototyping",
        skillsgroup2item2:"Design systems",
        skillsgroup2item3:"User testing & feedback",
        skillsgroup2item4:"persona creation",
        skillsgroup2item5:"UX Research",
        skillsgroup2item6:"Accessibility",
        skillsgroup2item7:"AI visual content",

        skillsgroup3:"Project Management",
        skillsgroup3item1:"collaboration tools",
        skillsgroup3item2:"team lead",
        skillsgroup3item3:"project lead",

        skillsgroup4:"Creative skills",
        skillsgroup4item1:"sketching",
        skillsgroup4item2:"painting",
        skillsgroup4item3:"digital painting",

        quote1:"Code without love is just text.",
        quote2:"There are no problems, only solutions.",

        jobsH2:"Work Experience",
        job1_title:"UX/UI Designer & Web Developer",
        job1_company:"Network Publishing GmbH  - 2025",
        job1_location:"Cologne (Hybrid)",
        job1_description1:"Creation of modern, user-friendly & accessible designs",
        job1_description2:"Integration and adaptation of designs in TYPO3 using TypoScript, HTML and SCSS (responsive design)",

        job2_title:"UX/UI Designer",
        job2_company:"Sign:up GmbH - (2023-2024)",
        job2_location:"Duisburg - DE (Remote)",
        job2_description1:"Creation of user-friendly, user-oriented designs",
        job2_description2:"Close collaboration with developers",

        job3_title:"UX/UI Designer",
        job3_company:"Faktor E GmbH - (2021-2023)",
        job3_location:"Bonn - DE (Hybrid)",
        job3_description1:"Creation of user-friendly, user-oriented designs",
        job3_description2:"Close collaboration with developers",
        job3_description3:"HTML & CSS adaptations (responsive design)",
        job3_description4:"Project management",

        job4_title:"Graphic & Web Designer / Team lead",
        job4_company:"Hemd & Hoodie - (2017-2021)",
        job4_location:"Cologne - DE",
        job4_description1:"Management of a team of designers",
        job4_description2:"Development of designs (social media, advertising campaigns)",
        job4_description3:"Project management",

        job5_title:"Graphic & Web Designer",
        job5_company:"Hemd & Hoodie - (2014-2017)",
        job5_location:"Cologne - DE",
        job5_description1:"Development of designs (social media, advertising campaigns, magazines, etc.)",

        job6_title:"Graphic & Web Designer",
        job6_company:"Hellbrecht Optics - 2014",
        job6_location:"Hilden - DE",
        job6_description1:"Development of designs for e-commerce, advertising campaigns, etc.",

        job7_title:"Graphic & Web Designer",
        job7_company:"LoFi-Merchandise - (2012-2014)",
        job7_location:"Cologne - DE",
        job7_description1:"Design creation for bands and festivals",
        job7_description2:"Shopfront decoration (graffiti, painting, stickers, etc.)",


        languages: "Languages",
        languagesFRDE: "Native",
        languagesEN: "Fluent",
        languagesES: "Intermediate",

        hobbies:"Hobbies",
        hobbiesText:"I am passionate about everything related to science fiction, comics, graphic novels and other fantastic worlds. I love spending time with my wife, my child and my friends. Likewise, I am also interested in nature, gardening and the environment, drawing, tinkering with my bicycles, my cat, video games, reading and role-playing games. ",

        projectsH2:"Projects",
        projectsText1:"Force Field is a personal project — a small Next.js app where I bring together my writing and cover art. It’s a space where I can combine different skills and experiment with design and development.",
        projectsText2:" Rooted was a group project created with friends and colleagues, inspired by our shared love of plants (and clean code). We worked in sprints, reviewed each other’s code, brainstormed, pair-coded, and learned a lot while having fun. I hope you’ll enjoy exploring both of these projects as much as I enjoyed building them.",

        trainingH2:"Qualifications",
        training1H3:"Web Developer",
        training2H3:"UX/UI Designer",
        training3H3:"JS & PHP basics",
        training4H3:"Applied arts and graphic design",
        training5H3:"A-levels in engineering sciences",

        linksH2:"You can find me here as well:",

    },
    fr: {
        welcome: "Bienvenue",
        availability: "Disponible",
        introH1:"Je crée des designs intuitifs à utiliser et réalistes à construire.",
        introH2: "Salut, je m'appelle Levin",
        introP: "Designer UX/UI et développeur front-end avec plus de 13 ans d'expérience.",
        introP2: "Je conçois et développe des produits digitaux intuitifs et accessibles, de la conception à la production. Je travaille à la croisée des besoins des utilisateurs, du design visuel et de la faisabilité technique. Je donne forme aux idées grâce à la recherche et au développement de prototypes, avant de soutenir une mise en œuvre claire et réaliste avec les développeurs (ou de la réaliser moi-même).",
        introP3:"En bref : je manipule des pixels, je pose les bonnes questions et j'aide mon équipe à créer des interfaces agréables à utiliser et faciles à maintenir.",
        introList1:"Designer UX/UI avec une forte orientation produit",
        introList2:"Bonne maîtrise du front-end (HTML, CSS/SCSS, React, TYPO3)",
        introList3:" Axé sur la conception, attentif à la mise en œuvre",
        introList4:"Plus de 13 ans d'expérience au sein d'agences et d'équipes commerciales",
        introList5:"Basé en Europe, favorable au télétravail",
        ctaText:"Intéressé(e) par mon profil ?",
        ctaLabel:"Contactez-moi dès maintenant",
        skillsH2:"Compétences",
        skillsgroup1:"Développement Web",

        skillsgroup2:"UX/UI & Design",
        skillsgroup2item1:"Prototypage",
        skillsgroup2item2:"Systèmes de design",
        skillsgroup2item3:"Tests utilisateurs & feedback",
        skillsgroup2item4:"création persona",
        skillsgroup2item5:"Recherche UX",
        skillsgroup2item6:"Accessibilité",
        skillsgroup2item7:"Création d'images avec l'IA",

        skillsgroup3:"Méthodologies & Gestion de projets",
        skillsgroup3item1:"Outils de collaboration",
        skillsgroup3item2:"Direction d’équipe",
        skillsgroup3item3:"Coordination de projets",

        skillsgroup4:"Compétences créatives",
        skillsgroup4item1:"Déssin",
        skillsgroup4item2:"DAO",
        skillsgroup4item3:"Peinture",

        quote1:"Le code sans amour, ce n'est que du texte.",
        quote2:"Il n'y a pas de problemes, que des solutions.",

        jobsH2:"Expérience",
        job1_title:"UX/UI Designer & Développeur Web",
        job1_company:"Network Publishing GmbH  - 2025",
        job1_location:"Cologne - DE (Hybride)",
        job1_description1:"Création de webdesigns accessibles et orientés utilisateurs",
        job1_description2:"Intégration et adaptation des designs sous TYPO3 avec TypoScript, HTML et SCSS (responsive design)",

        job2_title:"UX/UI Designer",
        job2_company:"Sign:up GmbH - (2023-2024)",
        job2_location:"Duisburg - DE (Télétravail)",
        job2_description1:"Création de webdesigns accessibles et orientés utilisateurs",
        job2_description2:"Collaboration étroite avec les développeurs",

        job3_title:"UX/UI Designer",
        job3_company:"Faktor E GmbH - (2021-2023)",
        job3_location:"Bonn - DE (Hybride)",
        job3_description1:"Création de webdesigns accessibles et orientés utilisateurs",
        job3_description2:"Collaboration étroite avec les développeurs",
        job3_description3:"Adaptations HTML & CSS (responsive design)",
        job3_description4:"Management de projets",

        job4_title:"Graphiste & Web Designer / Responsable d'équipe",
        job4_company:"Hemd & Hoodie - (2017-2020)",
        job4_location:"Cologne - DE",
        job4_description1:"Direction d'équipe de designers",
        job4_description2:"Création de designs (réseaux sociaux, campagnes publicitaires)",
        job4_description3:"Management de projets",

        job5_title:"Graphiste & Web Designer",
        job5_company:"Hemd & Hoodie - (2014-2017)",
        job5_location:"Cologne - DE",
        job5_description1:"Création de designs (médias sociaux, campagnes publicitaires, magazines, etc)",

        job6_title:"Graphiste & Web Designer",
        job6_company:"Hellbrecht Optics - 2014",
        job6_location:"Hilden - DE",
        job6_description1:"Création de designs pour l'E-commerce, campagnes publicitaires…",

        job7_title:"Graphic & Web Designer",
        job7_company:"LoFi-Merchandise - (2012-2014)",
        job7_location:"Cologne - DE",
        job7_description1:"Création de designs pour groupes de musique et festivals",
        job7_description2:"Décoration de la surface du magasin (graffiti, peinture, stickers, etc.)",

        languages: "Langues",
        languagesFRDE: "Langue maternelle",
        languagesEN: "Compétent",
        languagesES: "Intermédiaire",

        hobbies:"Loisirs",
        hobbiesText:"Je suis passionné par tout ce qui touche à la science-fiction, aux comics, aux BD et autres univers imaginaires, j’adore passer du temps avec ma femme, mon enfant et mes amis. Je m’intéresse aussi à la nature, au jardinage et à l’environnement, au dessin, ainsi qu’au bricolage de mes vélos, à mon chat, aux jeux vidéo, à la lecture et aux jeux de rôle.",

        projectsH2:"Projets",
        projectsText1:"Force Field est un projet personnel, une petite application Next.js où je rassemble mes écrits et mes couvertures d'histoires. C'est un espace dans lequel je peux combiner différentes compétences et expérimenter le design et le développement.",
        projectsText2:"Rooted était un projet collectif créé avec des amis et des collègues, inspiré par notre amour partagé des plantes (et du code). Nous avons travaillé par sprints, revu le code de chacun, réfléchi ensemble, codé en binôme et beaucoup appris tout en nous amusant. J'espère que vous prendrez autant de plaisir à découvrir ces deux projets que j'en ai pris à les créer.",

        trainingH2:"Formations",
        training1H3:"Développeur Web",
        training2H3:"UX/UI Designer",
        training3H3:"Cours de base JS & PHP",
        training4H3:"Arts appliqués et graphisme",
        training5H3:"Baccalauréat sciences de l'ingénieur",

        linksH2:"Retrouvez-moi également ici:",
    },
    de: {
        welcome:"Willkommen",
        availability: "Verfügbar",
        introH1:"Ich erstelle Designs, die intuitiv zu bedienen und realistisch umsetzbar sind.",
        introH2: "Hi, ich bin Levin",
        introP: "UX/UI-Designer und Frontend-Entwickler mit über 13 Jahren Erfahrung.",        
        introP2: "Ich entwerfe und entwickle intuitive, barrierefreie digitale Produkte vom Konzept bis zur Produktion. Ich arbeite an der Schnittstelle zwischen Nutzerbedürfnissen, visuellem Design und technischer Machbarkeit – ich forme Ideen durch Recherche und Prototyping und unterstütze dann eine saubere, realistische Umsetzung mit Entwicklern (oder entwickle sie selbst).",
        introP3:"Kurz gesagt: Ich schiebe Pixel, stelle die richtigen Fragen und helfe mein Team dabei, Erlebnisse zu schaffen, die sich gut anfühlen und gut zu pflegen sind.",
        introList1:"UX/UI-Designer mit ausgeprägtem produktorientiertem Denken",
        introList2:"Erfahrung mit Frontend-Technologien (HTML, CSS/SCSS, React, TYPO3)",
        introList3:"Designgesteuert, umsetzungsorientiert",
        introList4:"Über 13 Jahre Erfahrung in Agentur- und Produktteams",
        introList5:"In Europa angesiedelt, remote-freundlich",
        ctaText:"Wollen wir zusammenarbeiten?",
        ctaLabel:"Mich jetzt Kontaktieren",

        skillsH2:"Fähigkeiten",
        skillsgroup1:"Webentwicklung",

        skillsgroup2:"UX/UI & Design",
        skillsgroup2item1:"Prototyping",
        skillsgroup2item2:"Design systems",
        skillsgroup2item3:"User testing & feedback",
        skillsgroup2item4:"Persona Erstellung",
        skillsgroup2item5:"UX Research",
        skillsgroup2item6:"Barrierefreiheit",
        skillsgroup2item7:"KI Bildgenerierung",

        skillsgroup3:"Projektmanagement",
        skillsgroup3item1:"Kollaborationstools",
        skillsgroup3item2:"Teamleitung",
        skillsgroup3item3:"Projektkoordination",

        skillsgroup4:"Kreative Fähigkeiten",
        skillsgroup4item1:"Zeichnen",
        skillsgroup4item2:"Digitales Zeichnen",
        skillsgroup4item3:"Malen",

        quote1:"Code ohne Liebe ist nur Text.",
        quote2:"Es gibt keine Probleme, nur Lösungen.",

        jobsH2:"Berufserfahrung",
        job1_title:"UX/UI Designer & Web Developer",
        job1_company:"Network Publishing GmbH - 2025",
        job1_location:"Köln (Hybrid)",
        job1_description1:"Entwicklung moderner, benutzerfreundlicher und barrierefreier Designs",
        job1_description2:"Integration und Anpassung von Designs in TYPO3 unter Verwendung von TypoScript, HTML und SCSS (Responsive Design)",

        job2_title:"UX/UI Designer",
        job2_company:"Sign:up GmbH - (2023-2024)",
        job2_location:"Duisburg - DE (Remote)",
        job2_description1:"Erstellung benutzerfreundlicher, benutzerorientierter Designs",
        job2_description2:"Enge Zusammenarbeit mit Entwicklern",

        job3_title:"UX/UI Designer",
        job3_company:"Faktor E GmbH - (2021-2023)",
        job3_location:"Bonn - DE (Hybrid)",
        job3_description1:"Erstellung benutzerfreundlicher, benutzerorientierter Designs",
        job3_description2:"Enge Zusammenarbeit mit Entwicklern",
        job3_description3:"HTML- und CSS-Anpassungen (Responsive Design)",
        job3_description4:"Projektmanagement",

        job4_title:"Graphic & Web Designer / Team Lead",
        job4_company:"Hemd & Hoodie - (2017-2020)",
        job4_location:"Köln - DE",
        job4_description1:"Leitung eines Teams von Designern",
        job4_description2:"Entwicklung von Designs (Social Media, Werbekampagnen)",
        job4_description3:"Projektmanagement",

        job5_title:"Graphic & Web Designer",
        job5_company:"Hemd & Hoodie - (2014-2017)",
        job5_location:"Köln - DE",
        job5_description1:"Entwicklung von Designs (Social Media, Werbekampagnen, Zeitschriften usw.)",

        job6_title:"Graphic & Web Designer",
        job6_company:"Hellbrecht Optics - 2014",
        job6_location:"Hilden - DE",
        job6_description1:"Entwicklung von Designs für E-Commerce, Werbekampagnen usw.",

        job7_title:"Graphic & Web Designer",
        job7_company:"LoFi-Merchandise - (2012-2014) ",
        job7_location:"Köln - DE",
        job7_description1:"Design-Entwicklung für Bands und Festivals",
        job7_description2:"Shop- & Schaufensterdekoration (Graffiti, Malerei, Aufkleber usw.)",

        languages: "Sprachen",
        languagesFRDE: "Muttersprache",
        languagesEN: "Fließend",
        languagesES: "Fortgeschrittener Anfänger",

        hobbies:"Hobbies",
        hobbiesText:"Ich interessiere mich leidenschaftlich für alles, was mit Science-Fiction, Comics, Graphic Novels und anderen fantastischen Welten zu tun hat. Ich verbringe gerne Zeit mit meiner Frau, meinem Kind und meinen Freunden. Außerdem interessiere ich mich für Natur, Gartenarbeit und Umwelt, Zeichnen, Basteln an meinen Fahrrädern, meine Katze, Videospiele, Lesen und Rollenspiele. ",

        projectsH2:"Projekte",
        projectsText1:"Force Field ist ein persönliches Projekt – eine kleine Next.js-App, in der ich meine Texte und Cover-Art zusammenführe. Es ist ein Raum, in dem ich verschiedene Fähigkeiten kombinieren und mit Design und Entwicklung experimentieren kann.",
        projectsText2:" Rooted war ein Gruppenprojekt, das ich mit Freunden und Kollegen ins Leben gerufen habe, inspiriert von unserer gemeinsamen Liebe zu Pflanzen (und sauberem Code). Wir haben in Sprints gearbeitet, den Code der anderen überprüft, Brainstorming betrieben, gemeinsam programmiert und dabei viel gelernt und Spaß gehabt. Ich hoffe, Ihnen macht die Erkundung dieser beiden Projekte genauso viel Spaß wie mir ihre Entwicklung.",

        trainingH2:"Schulungen",
        training1H3:"Webentwickler",
        training2H3:"UX/UI Designer",
        training3H3:"JS & PHP Basics",
        training4H3:"Angewandte Kunst und Grafik Design",
        training5H3:"Abitur in Ingenieurwissenschaften",

        linksH2:"Sie finden mich auch hier:",
    }
};
